Builds:
  - versionName: 0.1.79
    versionCode: 79
    commit: 0.1.79
    subdir: app
    gradle:
      - yes
    ndk: r30
    output: app/release/app-universal-release-unsigned.apk

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 0.1.79
CurrentVersionCode: 79
