Builds:
  - versionName: 0.1.77
    versionCode: 77
    commit: 0.1.77
    subdir: app
    gradle:
      - yes
    ndk: r30
    output: app/release/app-universal-release-unsigned.apk

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 0.1.77
CurrentVersionCode: 77
