package com.ztftrue.music.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00677d)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFb2ebff)
val md_theme_light_onPrimaryContainer = Color(0xFF001f27)
val md_theme_light_secondary = Color(0xFF006a65)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFF6ff7ed)
val md_theme_light_onSecondaryContainer = Color(0xFF00201e)
val md_theme_light_tertiary = Color(0xFF7b5800)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdea6)
val md_theme_light_onTertiaryContainer = Color(0xFF271900)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFfbfcfe)
val md_theme_light_onBackground = Color(0xFF191c1d)
// background color
val md_theme_light_surface = Color(0xFFfbfcfe)
val md_theme_light_onSurface = Color(0xFF191c1d)
// slider color slider uncovered and enable
val md_theme_light_surfaceVariant = Color(0xFFdbe4e8)
val md_theme_light_onSurfaceVariant = Color(0xFF40484b)
// button border
val md_theme_light_outline = Color(0xFF70787c)
val md_theme_light_inverseOnSurface = Color(0xFFF9EFE7)
val md_theme_light_inverseSurface = Color(0xFF34302A)
val md_theme_light_inversePrimary = Color(0xFFFFB951)
val md_theme_light_surfaceTint = Color(0xFF825500)
val md_theme_light_outlineVariant = Color(0xFFD3C4B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF59d5f8)
val md_theme_dark_onPrimary = Color(0xFF003642)
val md_theme_dark_primaryContainer = Color(0xFF004e5e)
val md_theme_dark_onPrimaryContainer = Color(0xFFb2ebff)
val md_theme_dark_secondary = Color(0xFF4ddbd1)
val md_theme_dark_onSecondary = Color(0xFF003734)
val md_theme_dark_secondaryContainer = Color(0xFF00504c)
val md_theme_dark_onSecondaryContainer = Color(0xFF6ff7ed)
val md_theme_dark_tertiary = Color(0xFFf6bd48)
val md_theme_dark_onTertiary = Color(0xFF412d00)
val md_theme_dark_tertiaryContainer = Color(0xFF5d4200)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdea6)
val md_theme_dark_error = Color(0xFFffb4ab)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000a)
val md_theme_dark_onErrorContainer = Color(0xFFffdad6)
val md_theme_dark_background = Color(0xFF191c1d)
val md_theme_dark_onBackground = Color(0xFFe1e3e4)
val md_theme_dark_surface = Color(0xFF191c1d)
val md_theme_dark_onSurface = Color(0xFFe1e3e4)
val md_theme_dark_surfaceVariant = Color(0xFF40484b)
val md_theme_dark_onSurfaceVariant = Color(0xFFbfc8cc)
val md_theme_dark_outline = Color(0xFF899296)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
val md_theme_dark_inverseSurface = Color(0xFFEAE1D9)
val md_theme_dark_inversePrimary = Color(0xFF850000)
val md_theme_dark_surfaceTint = Color(0xFFFFB951)
val md_theme_dark_outlineVariant = Color(0xFF4F4539)
val md_theme_dark_scrim = Color(0xFF000000)

